services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: opp-keycloak
    restart: unless-stopped

    command:
      - start-dev
      - --import-realm

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:?KEYCLOAK_ADMIN_USERNAME is required}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:?KEYCLOAK_ADMIN_PASSWORD is required}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://opp-keycloak-postgresql:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME:?KEYCLOAK_DB_USERNAME is required}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:?KEYCLOAK_DB_PASSWORD is required}

      # Bật HTTPS trực tiếp trên Keycloak
      KC_HTTP_ENABLED: "false"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/keycloak.key

      # Phải đúng với domain hoặc IP trong chứng chỉ
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:?KEYCLOAK_HOSTNAME is required}
      KC_HOSTNAME_STRICT: "false"

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

      TZ: ${TZ:-Asia/Bangkok}

    ports:
      - "${KEYCLOAK_HTTPS_PORT:-8443}:8443"

    volumes:
      - ./realm:/opt/keycloak/data/import:ro
      - ./certs/keycloak.crt:/opt/keycloak/conf/keycloak.crt:ro
      - ./certs/keycloak.key:/opt/keycloak/conf/keycloak.key:ro
    networks:
      - auth-network

networks:
  auth-network:
    name: opp-auth-network
    external: true
