apiVersion: v1
kind: Secret
metadata:
  name: <APP_NAME>-secret
  namespace: <NAMESPACE>
type: Opaque
stringData:
  <SECRET_KEY_1>: "<SECRET_VALUE_1>"
  <SECRET_KEY_2>: "<SECRET_VALUE_2>"
  <SECRET_KEY_3>: "<SECRET_VALUE_3>"
