apiVersion: v1
kind: PersistentVolume
metadata:
  name: <PV_NAME>
spec:
  capacity:
    storage: <PV_STORAGE>
  accessModes:
    - <ACCESS_MODE>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: <STORAGE_CLASS_NAME>
  nfs:
    path: <NFS_PATH>
    server: <NFS_SERVER>
